### ISSUE TITLE
Half pixels are dead

### ISSUE THREAD

**Issue by hashtala** [imliubo/MLX90640-With-STM32#2]
![received_633131857534943](https://user-images.githubusercontent.com/44754948/78413580-0ce08980-7629-11ea-9ca7-14c36506e7d3.png)

I have no idea what the problem could be, any suggestions ?

**Comment by imliubo** [comment]
It seems that you only read subpage 1 of data. In chess mode, two pages of data should be merged into one page of data. You can refer to page 15 of the datasheet.
Which fream rate did you set?And the I2C clock frequency is?

**Comment by hashtala** [comment]
thanks for the response.

I for the evaluation I just copied your main code.Yes I am i  chess mode, I changed frame rate to 4Hz and I believe I2C clock is 100khz. should I go for 400khz ?

**Comment by hashtala** [comment]
Okay I solved it 

Turns out you have to do:
int status = MLX90640_GetFrameData(MLX90640_address, mlx90640Frame);
2 times before getting Vdd or doing calculations 

cheers
